### ISSUE TITLE
LM conflicts with Iris

### ISSUE THREAD

**Issue by Cjnator38** [MC-Legacy-Projects/Legacy-Mipmaps#3]
I was gonna try and bring up to omo adding Legacy Mipmaps back to Re-Console, but since 0.7.0 added Iris Shaders, this probably might not be possible right now. As it turns out, Legacy Mipmaps cannot be used when the Iris mod is loaded. LM works fine without Iris.

Here's the crash report: https://mclo.gs/vNoMC2x

**Comment by Permdog99** [comment]
Fixed a while back. Closing.
